
services:

  mysql:
    image: mysql:8.4
    container_name: mysql-tareas
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: tareasdb

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: .
    container_name: tareas-api

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  mysql-data: